### PR TITLE
Added : The sample web application project for claims-based authentication of ID-Federation by WIF

### LINKED ISSUE #7: Research to support claims-based authentication of ID-Federation by WIF
# Requirement
To support ID-Federation with WIF(Windows Identity Foundation) in OpenTouryo, please add the sample code [here](https://github.com/OpenTouryoProject/SampleProgram/tree/master/ASPNET/ID-Federation).

- This sample is "preliminary investigation" "to support".
- This sample does not need to use the OpenToutryo.

## About support configurations
This program is required that it support two configurations:

- [Single IdP configuration : ASP.NET WebSite is connecting by federation trust relationship with ADFS or AZAD](http://www.agileit.com/single-sign-on-sso-for-office-365-and-other-cloud-services/).  
  - ASP.NET WebSite - ( connecting by FTR ) - ADFS(ADDS)
  - ASP.NET WebSite - ( connecting by FTR ) - AZAD

- Hybrid IdP configuration : WebSite is connecting by federation trust relationship with ADFS over AZAD or ADFS Proxy. e.g. : [Diagram 1](http://blogs.technet.com/cfs-file.ashx/__key/communityserver-blogs-components-weblogfiles/00-00-00-56-58-metablogapi/2234.image_5F00_8.png), [Diagram 2](http://www.slideshare.net/kthrtty/101102-ms-techfielderidaasandazurefinal/35).
  - ASP.NET WebSite - ( connecting by FTR ) - AZAD or ADFS Proxy - ( connecting by FTR ) - ADFS(ADDS)

## About implementation
However, the two configurations have the difference about only infrastructure.
Therefor,  there is a possibility that maybe there is no need to change the application.

First, you must realize the claims-based authentication in the Single IdP configuration environment.

# Terminology
- WIF : Windows Identity Foundation
- ADDS : Active Directory Domain Services
- ADFS : Active Directory Federation Services 
- AZAD : Azure Active Directory
- IdP : Identity Provider ( = ADDS )
  - CP : Claim Provider( = Idp at WS-Federation model)
- STS : Security Token Service ( = ADFS or AZAD )
- SP : Service Provider( = ASP.NET WebSite)
  - RP : Relying Party( = SP at WS-Federation model)
- FTR : Federation Trust Relationship

- In the case of Hybrid structure, STS is classified into two types.
  - SP side STS : AZAD or ADFS Proxy
  - IDP side STS : ADFS

Service Providers, Identity Providers & Security Token Services
http://www.empowerid.com/learningcenter/technologies/service-identity-providers

### PR DESCRIPTION
**Pull request by daisukenishino**
fixed #7

### CODE REVIEW

**Comment by yusukemaegawa** [comment]
@daisukenishino 

> fixed #7 

Above issue describes as follows.

> # Requirement
> To support ID-Federation with WIF(Windows Identity Foundation) in OpenTouryo, please add the sample code [here](https://github.com/OpenTouryoProject/SampleProgram/tree/master/ASPNET/ID-Federation).

But the sample program in this pull request does not use OpenTouryo.
Therefore, I do not understand how this sample program is related to OpenTouryo.

Please explain.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

>Please explain.

The sample repository contains programs that not use the OpenTouryo.

And, This sample is "preliminary investigation" "to support".

>"To support" ID-Federation with WIF(Windows Identity Foundation) in OpenTouryo,

Authentication code of this sample is added to *.config file or base class 2 as a reference.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

>And, This sample is "preliminary investigation" "to support".

Issue #7 does not describe "preliminary investigation".
Therefore, I do not understand how this sample program is related to OpenTouryo.

I think that you should specify "preliminary investigation" in issue #7, otherwise I do not understand the goal of this issue.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Please check that it has been added the description at the beginning.
https://github.com/OpenTouryoProject/SampleProgram/issues/7#issue-78489895

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Please check that it has been added the description at the beginning.
https://github.com/OpenTouryoProject/SampleProgram/issues/7#issue-78489895

**Pull request merged**
