### PR TITLE
The location of the sample of "AsynchronousCall" has been moved.

### PR DESCRIPTION
**Pull request by daisukenishino**
Move [/SampleProgram/Other/Asynchronous/](https://github.com/OpenTouryoProject/SampleProgram/tree/master/Other/Asynchronous)
To [/SampleProgram/PrototypeModel/AsynchronousCall/](/SampleProgram/PrototypeModel/)

### CODE REVIEW

**Comment by yusukemaegawa** [comment]
@daisukenishino 

What is the purpose of changing the file path?

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Review of the structure is needed by the expansion of the sample.
The samples such as a pure sample and code snippet are placed at the position of the folder of the status quo.

All of the prototypical sample of the OpenTouryo is moved to "[/SampleProgram/PrototypeModel/](https://github.com/OpenTouryoProject/SampleProgram/tree/master/PrototypeModel)".
I think that [jqGridandWCF](https://github.com/OpenTouryoProject/SampleProgram/tree/master/ASPNET/WebForm/jqGridandWCF) also will be moved the location.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

> https://github.com/OpenTouryoProject/SampleProgram/pull/18#issuecomment-208152112

Sorry. I can not understand the **purpose** of this pull request.

Why did you need to change the file path?
What kind of samples will be stored in PrototypeModel folder?

**Comment by daisukenishino** [comment]
@yusukemaegawa 

@yusukemaegawa 

>Why did you need to change the file path?

I retouched.
see : https://github.com/OpenTouryoProject/SampleProgram/pull/18#issuecomment-208152112

>What kind of samples will be stored in PrototypeModel folder?

I think that all of the prototypical sample of the OpenTouryo should be moved to "[/SampleProgram/PrototypeModel/](https://github.com/OpenTouryoProject/SampleProgram/tree/master/PrototypeModel)".

**Comment by yusukemaegawa** [comment]
@daisukenishino 

> Sample program repository would be becoming one of the major outputs target of this project.

If so, how about removing old sample, and reviewing the structure?
(If you only change the file path, the size of SampleProgram repository does not become small.)

And, sorry for silly question.
Why do you name the folder "Prototype**Model**"?
Even if the name of the folder is "Prototype", I think that others can understand the purpose of the folder.
What is the meaning of **Model**?

**Comment by daisukenishino** [comment]
@yusukemaegawa 

>Even if the name of the folder is "Prototype", I think that others can understand the purpose of the folder. What is the meaning of Model?

see : プロトタイプモデルとは - IT用語辞典 Weblio辞書  
http://www.weblio.jp/content/%E3%83%97%E3%83%AD%E3%83%88%E3%82%BF%E3%82%A4%E3%83%97%E3%83%A2%E3%83%87%E3%83%AB

This word does not mean a simple prototype,
I wanted to be included the meaning of the model to this word.

>If so, how about removing old sample, and reviewing the structure?
(If you only change the file path, the size of SampleProgram repository does not become small.)

Because the prototype model is able to explain its own architecture briefly,
and therefore there are no plans to remove these prototype model.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

SampleProgram repository contains a lot of useful sample programs.
But, the structure of this sample programs is not designed efficiently.
And, it takes time to find the appropriate sample.

In addition to it,
SampleProgram repository became major output destination of the deliverables of the project.
( For example, Sample of the authentication lineage pertinent to this. )

So, I want to organize the structure of this sample programs as follows.

https://github.com/OpenTouryoProject/SampleProgram/blob/maintenance/README.md

- PrototypeModel
  - aaa
- ASP.NET
  - bbb
- Azure
  - ccc
- Others
  - ddd

**Pull request merged**
